language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
notifications:
  slack:
    secure: c0Zn3NZsseGM8EikuVoTIS0bklZJYoJPXfxQNNkcElUeEsl0ptg8wLl17Hv0MLQ+05I2XUKyD4r3anPXtZoNc50II7e8IThDdcyX1QrbDR3bwsKGN7kLXHGr0d8Bmr3A6FdWcHrka/tojpXyaTsOXBtsF3PkyMX7hkHrktTKjo9sAMZ45CcjHVRR64Ewjamw/WdFrbpay+kRfk0PjV7JzG8leLVDlXsVHcVfikuFyCPsgBNc4s3TNk0eYL2WxQojaSe5qY0VGDX1pqngwiWsk/U2u0rCcbOQztV9NsWyfp88loHuGCywoFXu+l2dJgwpkXCboW0JhF8lTvkaFrqCGeMBesEUp9CfluCna24qLbeQjTFc5/w95apvfncPIrSh89nYEFc/6088mmXULRAG1OthlIsbZV/XDIlO9j7XRC5VMiXl3drDN3EioKNGyh8PNSdkFYWknr6lKu1YQO+nUORi2nb0BEehzLW9drw0PHgiPkaFrZY1pFv6UDk5JjuPEi0xe8fdiGNmgXJlNlNlPEM4zxSv60E+TsHlerhnMBCtNVG6teaesh//CY8KW7gLL8vaHjcz73I1i92hfXhUEkZfX7JjvfJL6MJM2C7Q/DQDJjHU4d8BDhrEyegcFFzM2vE6by+rx4BPz6PtsEc4c5JKaPd7+UlBZWZKUktM2zs=
